db:
  dsn: dev:dev123456@tcp(192.168.188.233:3306)/loan?charset=utf8mb4&parseTime=True&loc=UTC
leo:
  rpc: https://api.explorer.provable.com/v1
  net: testnet
  holder: aleo14s8rn8km6uqwatevtk9qyf6vut0vuce398ghklqggmvrfskr7cxsrx5p7a
  holder_pk : APrivateKey1zkpE9F5UXwGuE2ivoM3MVvJEzAdx5JQfEDeNjzAzWb6JMnF
bsc:
  rpc: https://bsc-testnet-rpc.publicnode.com
  chain_id: 97
  usdt: 0xd851D918C4970F91453f5Cf50CD59e6f38aE6D5b
  lp: 0xD856fEc774FA5E7CA8561DE9ef852cb0D94AFE77
  income: 0x___
  loan_contract: 0xe1354798516b08D65160CA5CB2C409b166699013
  caller: c4698e08f86bea243f5c5f08ef37ce883b51437e6a34e7922f25cf55fd32add0
service:
  port: 8899
job:
  aleo_price: 0 * * * * ?
  calculate_rate: 0 * * * * ?
  calculate_income: 0 0 * * * ?
log:
  level: debug
platform:
  receive_address: 0x4332B66D46761476B0A50A2F12EE6a17DaCe7247